export interface GenreCategory {
  name: string
  genres: string[]
}

export const GENRE_CATEGORIES: GenreCategory[] = [
  {
    name: "선택 안 함 (None)",
    genres: ["없음"]
  },
  {
    name: "K-Pop / J-Pop / Pop",
    genres: ["케이팝", "J-Pop", "일본 애니메이션 스타일", "팝", "댄스팝", "버블검 팝", "버블검 댄스", "버블검 베이스", "하이퍼팝", "얼터너티브 팝", "베드룸 팝", "드림 팝", "어쿠스틱 팝", "싱어송라이터"]
  },
  {
    name: "Ballad / Piano / BGM",
    genres: ["발라드", "피아노", "솔로 피아노", "감성 피아노", "시네마틱 피아노", "뉴에이지", "힐링 음악", "명상 음악", "수면 음악", "카페 BGM", "잔잔한 BGM"]
  },
  {
    name: "Rock / Metal / Alternative",
    genres: ["록", "헤비메탈", "메탈코어", "그런지", "펑크", "얼터너티브 록", "어쿠스틱 록", "슈게이즈", "포스트 록", "스래시 메탈", "데스 메탈", "블랙 메탈", "둠 메탈", "파워 메탈", "심포닉 메탈", "프로그레시브 메탈"]
  },
  {
    name: "R&B / Soul / Groove",
    genres: ["알앤비", "얼터너티브 R&B", "펑크/소울", "재즈 소울", "그루브", "그루브 펑크", "그루브 소울", "그루브 R&B", "그루브 하우스", "디스코 펑크", "시티팝 그루브"]
  },
  {
    name: "Hip-Hop / Electronic",
    genres: ["힙합", "EDM", "하우스", "테크노", "애시드 하우스", "애시드 테크노", "트랜스", "애시드 트랜스", "브레이크비트", "브레이크비트 트랜스", "UK 개러지", "투스텝", "정글", "드럼 앤 베이스", "드럼스텝", "덥스텝", "퓨처 베이스", "칠스텝", "앰비언트 테크노", "앰비언트 하우스", "덥 테크노", "일렉트로팝", "신스팝", "뉴웨이브"]
  },
  {
    name: "Chill / Retro / Internet",
    genres: ["로파이", "앰비언트", "시티팝", "디스코", "일렉트로스윙", "베이퍼웨이브", "슬러시웨이브", "칠신스", "카와이 퓨처 베이스", "알고레이브"]
  },
  {
    name: "Folk / Country / Blues",
    genres: ["트로트", "포크", "블루스", "블루스 록", "블루스 포크", "컨트리"]
  },
  {
    name: "Jazz / Classic / Stage",
    genres: ["재즈", "클래식", "오케스트라", "시네마틱", "빅 밴드", "스윙", "애시드 재즈", "아방가르드 재즈", "카바레", "오페라", "바버샵"]
  },
  {
    name: "Korean Traditional / Worship",
    genres: ["국악", "판소리", "민요", "국악 퓨전", "찬송가", "CCM", "가스펠", "성가대"]
  },
  {
    name: "World / Latin / Afro",
    genres: ["월드뮤직", "샹송", "파두", "보사노바", "삼바", "살사", "플라멩코", "탱고", "레게", "레게톤", "아프로비트", "라틴팝", "아프로 하우스", "아프로 트랩", "아프로 재즈", "아프로 록", "아프로스윙", "아프로피아노", "아프로-큐반 재즈", "바차타", "쿰비아", "메렝게", "칼립소", "스카", "마리아치", "케이준", "발칸 브라스 밴드", "아랍 팝", "아랍 클래식", "아랍 레게"]
  }
]

export const GENRE_TRANSLATIONS: Record<string, string> = {
  "없음": "None",
  "케이팝": "K-Pop",
  "일본 애니메이션 스타일": "J-Anime Style",
  "팝": "Pop",
  "댄스팝": "Dance Pop",
  "버블검 팝": "Bubblegum Pop",
  "버블검 댄스": "Bubblegum Dance",
  "버블검 베이스": "Bubblegum Bass",
  "하이퍼팝": "Hyperpop",
  "얼터너티브 팝": "Alt Pop",
  "베드룸 팝": "Bedroom Pop",
  "드림 팝": "Dream Pop",
  "어쿠스틱 팝": "Acoustic Pop",
  "싱어송라이터": "Singer-Songwriter",
  "발라드": "Ballad",
  "피아노": "Piano",
  "솔로 피아노": "Solo Piano",
  "감성 피아노": "Emotional Piano",
  "시네마틱 피아노": "Cinematic Piano",
  "뉴에이지": "New Age",
  "힐링 음악": "Healing",
  "명상 음악": "Meditation",
  "수면 음악": "Sleep",
  "카페 BGM": "Cafe BGM",
  "잔잔한 BGM": "Calm BGM",
  "록": "Rock",
  "헤비메탈": "Heavy Metal",
  "메탈코어": "Metalcore",
  "그런지": "Grunge",
  "펑크": "Punk",
  "얼터너티브 록": "Alt Rock",
  "어쿠스틱 록": "Acoustic Rock",
  "슈게이즈": "Shoegaze",
  "포스트 록": "Post Rock",
  "스래시 메탈": "Thrash Metal",
  "데스 메탈": "Death Metal",
  "블랙 메탈": "Black Metal",
  "둠 메탈": "Doom Metal",
  "파워 메탈": "Power Metal",
  "심포닉 메탈": "Symphonic Metal",
  "프로그레시브 메탈": "Prog Metal",
  "알앤비": "R&B",
  "얼터너티브 R&B": "Alt R&B",
  "펑크/소울": "Funk/Soul",
  "재즈 소울": "Jazz Soul",
  "그루브": "Groove",
  "그루브 펑크": "Groove Funk",
  "그루브 소울": "Groove Soul",
  "그루브 R&B": "Groove R&B",
  "그루브 하우스": "Groove House",
  "디스코 펑크": "Disco Funk",
  "시티팝 그루브": "City Pop Groove",
  "힙합": "Hip-Hop",
  "하우스": "House",
  "테크노": "Techno",
  "애시드 하우스": "Acid House",
  "애시드 테크노": "Acid Techno",
  "트랜스": "Trance",
  "애시드 트랜스": "Acid Trance",
  "브레이크비트": "Breakbeat",
  "브레이크비트 트랜스": "Breakbeat Trance",
  "UK 개러지": "UK Garage",
  "투스텝": "2-Step",
  "정글": "Jungle",
  "드럼 앤 베이스": "Drum & Bass",
  "드럼스텝": "Drumstep",
  "덥스텝": "Dubstep",
  "퓨처 베이스": "Future Bass",
  "칠스텝": "Chillstep",
  "앰비언트 테크노": "Ambient Techno",
  "앰비언트 하우스": "Ambient House",
  "덥 테크노": "Dub Techno",
  "일렉트로팝": "Electropop",
  "신스팝": "Synthpop",
  "뉴웨이브": "New Wave",
  "로파이": "Lo-Fi",
  "앰비언트": "Ambient",
  "시티팝": "City Pop",
  "디스코": "Disco",
  "일렉트로스윙": "Electro Swing",
  "베이퍼웨이브": "Vaporwave",
  "슬러시웨이브": "Slushwave",
  "칠신스": "Chillwave",
  "카와이 퓨처 베이스": "Kawaii Future Bass",
  "알고레이브": "Algorave",
  "트로트": "Trot",
  "포크": "Folk",
  "블루스": "Blues",
  "블루스 록": "Blues Rock",
  "블루스 포크": "Blues Folk",
  "컨트리": "Country",
  "재즈": "Jazz",
  "클래식": "Classical",
  "오케스트라": "Orchestral",
  "시네마틱": "Cinematic",
  "빅 밴드": "Big Band",
  "스윙": "Swing",
  "애시드 재즈": "Acid Jazz",
  "아방가르드 재즈": "Avant-Garde Jazz",
  "카바레": "Cabaret",
  "오페라": "Opera",
  "바버샵": "Barbershop",
  "국악": "Korean Traditional",
  "판소리": "Pansori",
  "민요": "Minyo",
  "국악 퓨전": "Gugak Fusion",
  "찬송가": "Hymn",
  "가스펠": "Gospel",
  "성가대": "Choir",
  "월드뮤직": "World",
  "샹송": "Chanson",
  "파두": "Fado",
  "보사노바": "Bossa Nova",
  "삼바": "Samba",
  "살사": "Salsa",
  "플라멩코": "Flamenco",
  "탱고": "Tango",
  "레게": "Reggae",
  "레게톤": "Reggaeton",
  "아프로비트": "Afrobeat",
  "라틴팝": "Latin Pop",
  "아프로 하우스": "Afro House",
  "아프로 트랩": "Afro Trap",
  "아프로 재즈": "Afro Jazz",
  "아프로 록": "Afro Rock",
  "아프로스윙": "Afroswing",
  "아프로피아노": "Amapiano",
  "아프로-큐반 재즈": "Afro-Cuban Jazz",
  "바차타": "Bachata",
  "쿰비아": "Cumbia",
  "메렝게": "Merengue",
  "칼립소": "Calypso",
  "스카": "Ska",
  "마리아치": "Mariachi",
  "케이준": "Cajun",
  "발칸 브라스 밴드": "Balkan Brass",
  "아랍 팝": "Arabic Pop",
  "아랍 클래식": "Arabic Classical",
  "아랍 레게": "Arabic Reggae"
}
